---
title: "cytokit examples"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cytokit examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  dev = "png",
  comment = "#>"
)
```

Load the package

```{r load}
library(cytokit)
```

# One-sample plots

Plot a t-SNE coloured by mean marker expression

```{r tsneByMeanMarkerExpression, fig.width = 6, fig.height = 4, echo = FALSE, eval = FALSE}

tsneByMeanMarkerExpression(pbmc, c("IL32", "CD2"))

```


Plot a t-SNE coloured by percentiles marker expression

```{r tsneByPercentilesMarkerExpression, fig.width = 6, fig.height = 4}

tsneByPercentileMarkerExpression(pbmc, c("IL32", "CD2"))

# No labels
tsneByPercentileMarkerExpression(pbmc, c("IL32", "CD2"), label = FALSE)


```

# Two-sample plots

Pariwise violin plot

```{r markerViolinPlot, fig.width = 6, fig.height = 4}

markerViolinPlot(pbmc, markers_pbmc, pbmc, "PBMC1", "PBMC2", "res.1", "res.1")

```


Heatmap of minimum % overlap of gene markers between clusters from two different samples:
(here, comparing one dataset to itself)

```{r heatmapPercentMarkerOverlap, fig.width = 5, fig.height = 4}

heatmapPercentMarkerOverlap(markers_pbmc, markers_pbmc, s1_name = "PBMC", s2_name = "PBMC")

```


# Helper functions

Subset data by gene and cluster

```{r fetchData}

head(fetchData(pbmc, "IL32", c(1, 2)))
head(fetchData(pbmc, c("IL32", "MS4A1"), c(1, 2), return_cluster = TRUE, return_cell = TRUE))

```
